### PR TITLE
Fix sending large files to client

### LINKED ISSUE #2989: E2: fileWrite with big files is broken
**Describe the bug**
New file downloading queue system is doodoo fart

**To Reproduce**
```golo
@name file torture test
@inputs 
@outputs 
@persist Numbers:string Iter Init:string File:number
@trigger

if( first() ){
    Init = "0 1 2 ":repeat(256)
}

event tick(){
    if( Iter < 128 ){
        Numbers = Numbers + Init
        Iter++
    }
    elseif(!File){
        File = 1
        print("writing " + Numbers:length() + " bytes")
        fileWrite(">e2shared/filetest.txt", Numbers)
    }
}
```
**Expected behavior**
File should eventually write

**Actual behavior**
It never does :trollface:

### PR DESCRIPTION
**Pull request by Fasteroid**
#2989

### CODE REVIEW

File: lua/entities/gmod_wire_expression2/core/files.lua [hunk 1]
```diff
@@ -348,14 +348,14 @@ local function flushFileBufferInner()
 
 				if strlen > 0 then
 					net.Start("wire_expression2_file_download")
-					net.WriteUInt(2, 2)
-					net.WriteUInt(strlen, 32)
-					net.WriteData(data:sub(index + 1), strlen)
+						net.WriteUInt(2, 2)
+						net.WriteUInt(strlen, 32)
+						net.WriteData(data:sub(index + 1, index + 1 + strlen), strlen)
```
Comment (Denneisk) [inline lua/entities/gmod_wire_expression2/core/files.lua:353]: Again, the substring is already limited by `WriteData` without needing to do extra addition.

**Review by Denneisk — APPROVED** [review]

File: lua/entities/gmod_wire_expression2/core/files.lua (hunk 1 above)
Comment (thegrb93) [reply lua/entities/gmod_wire_expression2/core/files.lua:353]: It's still currently making the substring function return a lot bigger of a string than it should which wastes cputime.

**Review by thegrb93 — APPROVED** [review]

**Comment by thegrb93** [comment]
The conflict can be resolved easily
