### PR TITLE
Throw explained lambda error (#3130 #3308)

### LINKED ISSUE #3130: Simple compiler bug
**Describe the bug**
Compiler bug

**To Reproduce**
Attempt to call nil lambda.
```
@persist A:function

A()
```

**Expected behavior**
Verbose error

**Error message**
`sv: Expression 2 (generic): Internal error 'addons/wire/lua/entities/gmod_wire_expression2/base/compiler.lua:1884: attempt to index local 'f' (a nil value)' at line 3, char 1`

### PR DESCRIPTION
**Pull request by Zvbhrf**
Fixes #3130 and #3308

(Sorry, I messed commit history a bit :P)

### CODE REVIEW

File: lua/entities/gmod_wire_expression2/base/compiler.lua [hunk 1]
```diff
@@ -1915,6 +1915,10 @@ local CompileVisitors = {
 				---@type E2Lambda
 				local f = expr(state)
 
+				if f == nil then
+                    state:forceThrow("An uninitialized lambda «" .. (data[1].data.value or "unknown") .. "» was called")
```
Comment (Denneisk) [inline lua/entities/gmod_wire_expression2/base/compiler.lua:1919]: May you change `«»` quotes to `()` just to match the style?

**Review by Denneisk — APPROVED** [review]
I'm still a supporter for the previous compiler writer's reason for not including this check, but I won't be too resistant if people still want it.
