### PR TITLE
Wirekeyboard compromise

### LINKED ISSUE #1354: Wire keyboard enter code changed
Hello, i want to ask why you changed wire keyboard enter code? It was 13 but now its 10. This broke compatibility with wiremod in other addons, all stuff what used those key code now broken. This including all e2's, wire inputs on entities what can use wire keyboard as input, etc.

### PR DESCRIPTION
**Pull request by Divran**
Fixes #1354

Adds a new checkbox which toggles the ascii value output of the enter key between 13 and 10. Old dupes will not have this value defined, so they will default to 13 (the old value). The checkbox defaults to 10, but can be toggled in the keyboard tool context menu.

(Side notes: All options are now displayed in the entity overlay)

### CODE REVIEW

**Comment by Divran** [comment]
Here we go again, @TomyLobo @Nebual @AbigailBuccaneer thoughts? Is this compromise good enough

File: lua/wire/stools/keyboard.lua [hunk 1]
```diff
@@ -41,12 +40,20 @@ function TOOL.BuildCPanel(panel)
...
 	})
+	panel:Help( "This is the key used to exit a keyboard. This option is clientside. Any keyboard you use, created by any player, will use this key." )
+
+	panel:CheckBox("Lock player controls on keyboard", "wire_keyboard_sync")
+	panel:Help( "When on, 'locks' the player into the keyboard, meaning any keys they press will not move their character around. When off, they can walk around while typing. This option is serverside, and will be saved on the keyboard through duplications." )
+	
+	panel:CheckBox("Automatic buffer clear", "wire_keyboard_autobuffer")
+	panel:Help( "When on, automatically removes the key from the buffer when the user releases it.\nWhen off, leaves all keys in the buffer until they are manually removed.\nTo manually remove a key, write any value to cell 0 to remove the first key, or write a specific ascii value to any address other than 0 to remove that specific key. This option is serverside, and will be saved on the keyboard through duplications.")
+
+	panel:CheckBox("Enter key ASCII output","wire_keyboard_enterkeyascii")
```
Comment (oldmud0) [inline lua/wire/stools/keyboard.lua]: Probably should be better described: `Use \n for ENTER key instead of \r`

Comment (Divran) [inline lua/wire/stools/keyboard.lua]: Sure, we could make this clearer, but there's a "Help" label directly below this which describes it in more detail

Comment (oldmud0) [inline lua/wire/stools/keyboard.lua]: It's just part of good UX practice. Both the title and description should be clear, rather than one relying on the other.

File: lua/wire/stools/keyboard.lua [hunk 2]
```diff
@@ -54,6 +54,6 @@ function TOOL.BuildCPanel(panel)
 	panel:CheckBox("Automatic buffer clear", "wire_keyboard_autobuffer")
 	panel:Help( "When on, automatically removes the key from the buffer when the user releases it.\nWhen off, leaves all keys in the buffer until they are manually removed.\nTo manually remove a key, write any value to cell 0 to remove the first key, or write a specific ascii value to any address other than 0 to remove that specific key. This option is serverside, and will be saved on the keyboard through duplications.")
 
-	panel:CheckBox("Enter key ASCII output","wire_keyboard_enterkeyascii")
+	panel:CheckBox("Use '\\n' for ENTER key instead of '\\r'","wire_keyboard_enterkeyascii")
```
Comment (oldmud0) [inline lua/wire/stools/keyboard.lua]: yay

**Comment by Divran** [comment]
Alright I'm going to merge this soon™ if no one objects

**Comment by Divran** [comment]
alright I used my admin privileges to forcibly merge this PR even though it didn't have any positive reviews by other wire developers because they're all a bunch of no-shows.
