### PR TITLE
Convert file extension to use netstream

### LINKED ISSUE #2989: E2: fileWrite with big files is broken
**Describe the bug**
New file downloading queue system is doodoo fart

**To Reproduce**
```golo
@name file torture test
@inputs 
@outputs 
@persist Numbers:string Iter Init:string File:number
@trigger

if( first() ){
    Init = "0 1 2 ":repeat(256)
}

event tick(){
    if( Iter < 128 ){
        Numbers = Numbers + Init
        Iter++
    }
    elseif(!File){
        File = 1
        print("writing " + Numbers:length() + " bytes")
        fileWrite(">e2shared/filetest.txt", Numbers)
    }
}
```
**Expected behavior**
File should eventually write

**Actual behavior**
It never does :trollface:

### PR DESCRIPTION
**Pull request by Denneisk**
Makes sending files between client and server use netstream.

Fixes #2989 

RFC:
- Should I move `process_filepath` in `cl_files.lua` to the server so I can remove the concmd for SP file management?

### CODE REVIEW

File: lua/entities/gmod_wire_expression2/core/cl_files.lua [hunk 1]
```diff
@@ -49,92 +44,48 @@ end
...
-				data = filedata
-			}
-
+			local data = file.Read(fullpath, "DATA") or ""
 			net.Start("wire_expression2_file_upload")
-				net.WriteUInt(1, 2)
-				net.WriteUInt(len, 32)
+				net.WriteBool(true)
+				net.WriteUInt(#data, 32)
+				net.WriteUInt(tonumber(util.CRC(data)), 32)
```
Comment (thegrb93) [inline lua/entities/gmod_wire_expression2/core/cl_files.lua:59]: netstream already does crc

File: lua/entities/gmod_wire_expression2/core/files.lua [hunk 2]
```diff
@@ -432,80 +403,37 @@ end
...
-				net.WriteString(queue[1].name)
-				net.WriteBool(ply:IsListenServerHost())
-			net.Send(ply)
 		end
 	end
 end)
 
-concommand.Add("wire_expression2_file_singleplayer", function(ply, cmd, args)
-	if not ply:IsListenServerHost() then ply:Kick("Do not use wire_expression2_file_singleplayer in multiplayer, unless you're the host!") end
+concommand.Add("wire_expression2_file_singleplayer", function(ply, _, args)
```
[the remark this answers is not in the document]
Comment (Denneisk) [reply lua/entities/gmod_wire_expression2/core/files.lua:435]: I believe the point of it was to avoid using networking at all but I don't mind doing that too much.

File: lua/entities/gmod_wire_expression2/core/files.lua [hunk 3]
```diff
@@ -6,10 +6,10 @@
 local cv_max_transfer_size = CreateConVar("wire_expression2_file_max_size", "300", { FCVAR_REPLICATED, FCVAR_ARCHIVE }, "Maximum file size in kibibytes.")
```
Comment (thegrb93) [inline lua/entities/gmod_wire_expression2/core/files.lua:6]: This can be increased to a 16 megabytes or something

**Review by thegrb93 — APPROVED** [review]

File: lua/entities/gmod_wire_expression2/core/files.lua (hunk 3 above)
Comment (Denneisk) [reply lua/entities/gmod_wire_expression2/core/files.lua:6]: I am curious of how users would make use of 16MB. 1MB is probably already more than enough.

Comment (Fasteroid) [reply lua/entities/gmod_wire_expression2/core/files.lua]: I have this set to 8192 on my server so that E2 raytracers can save images.  Those suckers can get big.

**Comment by Fasteroid** [comment]
@thegrb93 This broke uploading files, please test PRs before you merge them.
