### PR TITLE
E2 npc core touch ups

### LINKED ISSUE #2187: Error when running E:npcDisp(E) on npcs owned by other npcs in local & dedicated x64 server
Error:
lua/entities/gmod_wire_expression2/core/e2lib.lua:714: attempt to call method 'CPPIGetFriends' (a nil value)
Quick code link:
https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/e2lib.lua#L714

This has happened as well when using E:npcRelationshipByOwner(E,S,N)

Error happens when an npc is owned by another npc, this happened to me when a zombie died and "dropped" its headcrab. 
For a brief moment before the dead zombie truly despawns, it "owns" the headcrab.
A potential fix might entail adding a simple check to see if owner is a player before owner:CPPIGetFriends() is called.

### PR DESCRIPTION
**Pull request by Vurv78**
Fixes #2187

* Added compat with ``@strict`` for all functions
* Turned npcdisp enum functions into tables
* Removed use of C operators
* Fixed ``E2Lib.isFriend`` for non-player owners*

### CODE REVIEW

File: lua/entities/gmod_wire_expression2/core/npc.lua [hunk 1]
```diff
@@ -7,70 +7,84 @@ E2Lib.RegisterExtension("npc", true, "Allows controlling of NPCs.", "NPCs can be
...
 e2function void entity:npcGiveWeapon()
-	if !validNPC(this) || !isOwner(self,this) then return end
+	if not validNPC(this) then return self:throw("Entity e: is not a valid NPC!", nil) end
+	if not isOwner(self, this) then return self:throw("You do not own this NPC!", nil) end
 
 	local weapon = this:GetActiveWeapon()
-	if (weapon:IsValid()) then
-		if (weapon:GetClass() == "weapon_smg1") then return end
+	if weapon:IsValid() then
+		if weapon:GetClass() == "weapon_smg1" then return end
```
Comment (thegrb93) [inline lua/entities/gmod_wire_expression2/core/npc.lua:59]: Shouldn't this be ai_weapon_smg1?

**Comment by thegrb93** [comment]
Everything else looks good, just need to figure out if that line I mentioned is a bug or not

File: lua/entities/gmod_wire_expression2/core/npc.lua (hunk 1 above)
Comment (Vurv78) [reply lua/entities/gmod_wire_expression2/core/npc.lua:59]: Printed out weapon:GetClass() and it was weapon_smg1 (Also made sure to concat a string to it so garry prints wouldn't be deceiving me). Also tested using weapon_smg1 and got the same result.

I have no idea why we use ai_weapon_smg1 but I'm just gonna assume :Give() just allows ai_ as a prefix. Or maybe ai_ weapons are restricted to the default ones.
